### ISSUE TITLE
Failed to create symlink

### ISSUE THREAD

**Issue by tmexner-dev** [vjaykrsna/gsconnect-mount-manager#4]
`2025-07-31 15:09:59] [INFO] GSConnect Mount Manager started (PID: 58948)
[2025-07-31 15:09:59] [INFO] Configuration: poll_interval=5s, symlink_dir=/home/tobias/.gsconnect-mount, notifications=true
[2025-07-31 15:09:59] [INFO] Mount detected: sftp:host=192.168.178.47,port=1739
[2025-07-31 15:09:59] [INFO] Found matching device: 'Pixel 8' for IP 192.168.178.47
[2025-07-31 15:09:59] [INFO] Device name: '[2025-07-31 15:09:59] [INFO] Found matching device: 'Pixel 8' for IP 192.168.178.47
Pixel 8' (sanitized: '032m2025-07-31-150959-INFO-Found-matching-device-Pixel-8-for-IP-192.168.178.470m
Pixel-8')
[2025-07-31 15:09:59] [INFO] Found internal storage: /run/user/1000/gvfs/sftp:host=192.168.178.47,port=1739/storage/emulated/0
[2025-07-31 15:09:59] [INFO] Found 2 storage path(s)
[2025-07-31 15:09:59] [INFO] 🔖 Device bookmark added: [2025-07-31 15:09:59] [INFO] Found matching device: 'Pixel 8' for IP 192.168.178.47
Pixel 8
[2025-07-31 15:09:59] [ERROR] Failed to create symlink: [2025-07-31 15:09:59] [INFO] 🔖 Device bookmark added: [2025-07-31 15:09:59] [INFO] Found matching device: 'Pixel 8' for IP 192.168.178.47
Pixel 8
/home/tobias/.gsconnect-mount/032m2025-07-31-150959-INFO-Found-matching-device-Pixel-8-for-IP-192.168.178.470m
Pixel-8/
[2025-07-31 15:09:59] [ERROR] Failed to create symlink: [2025-07-31 15:09:59] [INFO] 🔖 Device bookmark added: [2025-07-31 15:09:59] [INFO] Found matching device: 'Pixel 8' for IP 192.168.178.47
Pixel 8
/home/tobias/.gsconnect-mount/032m2025-07-31-150959-INFO-Found-matching-device-Pixel-8-for-IP-192.168.178.470m
Pixel-8/Internal
[2025-07-31 15:09:59] [ERROR] Failed to create any symlinks, skipping flag creation`

I just installed the script, and I get bookmarks, but they are definitely not right and not working as intended. I think the device name is not being sanitized properly.

<img width="225" height="118" alt="Image" src="https://github.com/user-attachments/assets/46f7ac54-bf01-4458-bcfe-c24d602aeadb" />

**Comment by vjaykrsna** [comment]
My bad i forgot that i had to work on it, can you check if the issue is fixed,
i tried to fix it
i will be quicker this time 😅

**Comment by tmexner-dev** [comment]
Hey, thanks for the response, now the service crashes with the following error:
/home/tobias/.config/gsconnect-mount-manager/run.sh: line 488: local: can only be used in a function
gsconnect-mount-manager.service: Main process exited, code=exited, status=1/FAILURE

**Comment by tmexner-dev** [comment]
I tried to fix it by removing the local, but after that the service fails with the following error:
/home/tobias/.config/gsconnect-mount-manager/run.sh: line 491: find_result: command not found

**Comment by vjaykrsna** [comment]
i posted a new commit on the main branch without testing it well
i was closing my laptop so i pushed it to save progress and work with other device
i should have created a seperate branch my bad

**Comment by vjaykrsna** [comment]
> Hey, thanks for the response, now the service crashes with the following error: /home/tobias/.config/gsconnect-mount-manager/run.sh: line 488: local: can only be used in a function gsconnect-mount-manager.service: Main process exited, code=exited, status=1/FAILURE

update and check now
I am still working on it to improve it
but I hope your issue is fixed now

**Comment by tmexner-dev** [comment]
The log file seems not to be created now.
This is all the output prints now. The service still fails but without an error now.
```
cat /home/tobias/.config/gsconnect-mount-manager/gsconnect-mount-manager.log
cat: /home/tobias/.config/gsconnect-mount-manager/gsconnect-mount-manager.log: No such file or directory
tobias@tobias-PC:~/gsconnect-mount-manager$ journalctl --user -u gsconnect-mount-manager -f
Aug 26 09:41:32 tobias-PC run.sh[8362]: DEBUG: Checking if device directory exists: yes
Aug 26 09:41:32 tobias-PC systemd[1680]: gsconnect-mount-manager.service: Main process exited, code=exited, status=1/FAILURE
Aug 26 09:41:32 tobias-PC systemd[1680]: gsconnect-mount-manager.service: Failed with result 'exit-code'.
Aug 26 09:41:37 tobias-PC systemd[1680]: gsconnect-mount-manager.service: Scheduled restart job, restart counter is at 2.
Aug 26 09:41:37 tobias-PC systemd[1680]: Started gsconnect-mount-manager.service - GSConnect Mount Manager.
Aug 26 09:41:39 tobias-PC run.sh[8614]: DEBUG: About to call create_device_structure
Aug 26 09:41:39 tobias-PC run.sh[8614]: DEBUG: Finished calling create_device_structure, device_dir=/home/tobias/.gsconnect-mount/Pixel-8
Aug 26 09:41:39 tobias-PC run.sh[8614]: DEBUG: Checking if device directory exists: yes
Aug 26 09:41:39 tobias-PC systemd[1680]: gsconnect-mount-manager.service: Main process exited, code=exited, status=1/FAILURE
Aug 26 09:41:39 tobias-PC systemd[1680]: gsconnect-mount-manager.service: Failed with result 'exit-code'.
```

**Comment by vjaykrsna** [comment]
i had a complete rewrite of the code and i finished it
can you do a fresh install and let me know
i seperated all the logging and device detection to avoid such issues
